login_view/accounts/urls.py
#urlを通す

from django.urls import path
#views.py内のクラスをインポート
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView
)



#↓login_view　内のurls.pyにinclude
app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
]

login_view/login_view/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

login_view/accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin,UserManager
)

from django.urls import reverse_lazy

class UserManager(BaseUserManager):   #カスタムマネージャー
    #通常ユーザーを作成する場合の関数を定義、ログインするための設定
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Enter Email')
        user = self.model(
            username=username,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


class Users(AbstractBaseUser, PermissionsMixin):  #カスタムユーザーを作成、ユーザー名以外でログインしたい時
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=255)
    is_active = models.BooleanField(default=True)           #ログインの可否
    is_staff = models.BooleanField(default=False)           #管理画面のアクセス可否

    USERNAME_FIELD = 'username'                                #emailでログイン認証したいので、emailをユニークなフィールドとして指定
    #REQUIRED_FIELDS = ['username']

    objects = UserManager() #importしたUserManagerを指定

    def get_absolute_url(self):
        return reverse_lazy('accounts:home')

login_view/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password


#4つのフィールド作成 このフォームを使用してユーザー登録を行う
class RegistForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())


    class Meta:
        model = Users
        fields = ['username', 'age', 'email', 'password']

    def save(self, commit=False):
        user = super().save(commit=False)
        #パスワードが適切なものか
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

#ログインフォーム
class UserLoginForm(forms.Form):
    username = forms.CharField(label='ユーザー名')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())

login_view/accounts/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import CreateView, FormView
from .forms import RegistForm, UserLoginForm
#passwordが正しいものなのかチェックする
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

#ホーム画面
class HomeView(TemplateView):
    template_name = 'home.html'

#ユーザー登録するView
class RegistUserView(CreateView):
    template_name = 'regist.html'
    #form指定
    form_class = RegistForm  #accounts forms.py内に作成して、import


#ログイン画面
class UserLoginView(FormView):
    template_name = 'user_login.html'
    form_class = UserLoginForm

    def post(self, request, *args, **kwargs):
        username = request.POST['username']           #.get('email')
        password = request.POST['password']           #.get('password')
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
        return render(request, 'home.html', context={'value': username}) #return redirect('accounts:home')

           
class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:user_login')

login_view/templates/base.html
<!DOCTYPE html>
<html lang = 'ja'>
    <head>
        <meta charset = "utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <body>
        <nav class = "navbar navbar-expand-lg nabvar-light bg-light">
            <a class = "navbar-brand" href = "{% url 'accounts:home' %}">ホーム</a>>
            {% if user.is_authenticated %} <!--ログインしているとき-->
            <a class = "navbar-brand" href = "{% url 'accounts:user_logout' %}">ログアウト</a>>

            {% else %}
            <a class = "navbar-brand" href = "{% url 'accounts:user_login' %}">ログイン</a>>
            <a class = "navbar-brand" href = "{% url 'accounts:regist' %}">ユーザー登録</a>>

            {% endif %}
        </nav>
        {% block content %}{% endblock %} 
    </body>


    </head>>

</html>>    

login_view/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>ホーム画面です</h1>
{% if user.is_authenticated %}
<p>ようこそ!{{value}}さん</p>
{% endif %}
{% endblock %}

login_view/templates/regist.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}   
    {{ form.as_p }}    
    <input type="submit" value="ユーザー登録">
</form>

{% endblock %}

login_view/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ログイン">
</form>
 {% endblock %}